require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.colorscheme")
require("user.autopairs")
require("user.comment")
-- require("user.lualine")
require("user.feline")
require("user.project")
require("user.whichkey")
